openapi: 3.0.0
info:
  title: chatai-swagger
  version: 1.0.0
paths:
  '{{baseUrl}}/':
    get:
      summary: Home
      operationId: Home
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/threads/:thread_id/messages':
    post:
      summary: Add Messages
      operationId: Add Messages
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: thread_id
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
    get:
      summary: Get Messages
      operationId: Get Messages
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: thread_id
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/assistants':
    post:
      summary: Create Assistant
      operationId: Create Assistant
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
    get:
      summary: Get Assistants
      operationId: Get Assistants
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/threads':
    post:
      summary: Create Threads
      operationId: Create Threads
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/assistants/:assistant_id':
    delete:
      summary: Delete Assistant
      operationId: Delete Assistant
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: assistant_id
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/threads/:thread_id':
    get:
      summary: Get Thread
      operationId: Get Thread
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: thread_id
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/threads/:thread_id/runs':
    post:
      summary: Run Thread
      operationId: Run Thread
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: thread_id
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/audio/speech':
    post:
      summary: Audio Speech
      operationId: Audio Speech
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  undefined: {}
  '{{baseUrl}}/:provider/v1/batches':
    post:
      summary: Create Batch
      operationId: Create Batch
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: provider
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
    get:
      summary: List Batches
      operationId: List Batches
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: limit
          in: query
          description: ''
          required: false
          example: ''
        - name: after
          in: query
          description: ''
          required: false
          example: ''
        - name: provider
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/:provider/v1/batches/:batch_id':
    get:
      summary: Retrieve Batch
      operationId: Retrieve Batch
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: provider
          in: query
          description: ''
          required: true
          example: ''
        - name: batch_id
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/cache/delete':
    post:
      summary: Cache Delete
      operationId: Cache Delete
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/cache/flushall':
    post:
      summary: Cache Flushall
      operationId: Cache Flushall
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/cache/ping':
    get:
      summary: Cache Ping
      operationId: Cache Ping
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/cache/redis/info':
    get:
      summary: Cache Redis Info
      operationId: Cache Redis Info
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/chat/completions':
    post:
      summary: Chat Completion
      operationId: Chat Completion
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: model
          in: query
          description: ''
          required: false
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/completions':
    post:
      summary: Completion
      operationId: Completion
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: model
          in: query
          description: ''
          required: false
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/embeddings':
    post:
      summary: Embeddings
      operationId: Embeddings
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: model
          in: query
          description: ''
          required: false
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/:provider/v1/files/:file_id':
    delete:
      summary: Delete File
      operationId: Delete File
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: file_id
          in: query
          description: ''
          required: true
          example: ''
        - name: provider
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
    get:
      summary: Get File
      operationId: Get File
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: file_id
          in: query
          description: ''
          required: true
          example: ''
        - name: provider
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/:provider/v1/files/:file_id/content':
    get:
      summary: Get File Content
      operationId: Get File Content
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: file_id
          in: query
          description: ''
          required: true
          example: ''
        - name: provider
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/:provider/v1/files':
    get:
      summary: List Files
      operationId: List Files
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: purpose
          in: query
          description: ''
          required: false
          example: ''
        - name: provider
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/active/callbacks':
    get:
      summary: Active Callbacks
      operationId: Active Callbacks
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/health':
    get:
      summary: Health Endpoint
      operationId: Health Endpoint
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: model
          in: query
          description: ''
          required: false
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/health/liveliness':
    options:
      summary: Health Liveliness Options
      operationId: Health Liveliness Options
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
    get:
      summary: Health Liveliness
      operationId: Health Liveliness
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/health/readiness':
    options:
      summary: Health Readiness Options
      operationId: Health Readiness Options
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
    get:
      summary: Health Readiness
      operationId: Health Readiness
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/test':
    get:
      summary: Test Endpoint
      operationId: Test Endpoint
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/v1/images/generations':
    post:
      summary: Image Generation
      operationId: Image Generation
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/utils/supported_openai_params':
    get:
      summary: Supported Openai Params
      operationId: Supported Openai Params
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: model
          in: query
          description: ''
          required: true
          example: ''
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
  '{{baseUrl}}/utils/token_counter':
    post:
      summary: Token Counter
      operationId: Token Counter
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
      requestBody:
        $ref: '#/components/requestBodies/token_counter'
  '{{baseUrl}}/v1/moderations':
    post:
      summary: Moderations
      operationId: Moderations
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      parameters:
        - name: x-api-key
          in: header
          description: ''
          required: true
          example: '{{apiKey}}'
servers: []
components:
  schemas:
    audio_transcriptions:
      type: object
      properties:
        file:
          type: string
    create_file:
      type: object
      properties:
        purpose:
          type: string
        custom_llm_provider:
          type: string
        file:
          type: string
    token_counter:
      type: object
      properties:
        model:
          type: string
        prompt:
          type: string
        messages:
          type: string
  requestBodies:
    audio_transcriptions:
      content:
        'multipart/form-data:':
          schema:
            $ref: '#/components/schemas/audio_transcriptions'
      description: ''
      required: true
    create_file:
      content:
        'multipart/form-data:':
          schema:
            $ref: '#/components/schemas/create_file'
      description: ''
      required: true
    token_counter:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/token_counter'
      description: ''
      required: true
  securitySchemes: {}
